/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLojaRouteImport } from './routes/admin.loja'

const ResetarSenhaLazyRouteImport = createFileRoute('/resetar-senha')()
const MinhaContaLazyRouteImport = createFileRoute('/minha-conta')()
const MeusPedidosLazyRouteImport = createFileRoute('/meus-pedidos')()
const LoginLazyRouteImport = createFileRoute('/login')()
const EsqueciSenhaLazyRouteImport = createFileRoute('/esqueci-senha')()
const IndexLazyRouteImport = createFileRoute('/')()
const AdminIndexLazyRouteImport = createFileRoute('/admin/')()
const LojaSlugLazyRouteImport = createFileRoute('/loja/$slug')()
const AdminLojasLazyRouteImport = createFileRoute('/admin/lojas')()
const AdminLojaIndexLazyRouteImport = createFileRoute('/admin/loja/')()
const AdminLojaSegurancaLazyRouteImport = createFileRoute(
  '/admin/loja/seguranca',
)()
const AdminLojaPedidosLazyRouteImport = createFileRoute('/admin/loja/pedidos')()
const AdminLojaGaleriaLazyRouteImport = createFileRoute('/admin/loja/galeria')()
const AdminLojaEquipeLazyRouteImport = createFileRoute('/admin/loja/equipe')()
const AdminLojaConfiguracoesLazyRouteImport = createFileRoute(
  '/admin/loja/configuracoes',
)()
const AdminLojaCategoriasLazyRouteImport = createFileRoute(
  '/admin/loja/categorias',
)()
const AdminLojaCardapioLazyRouteImport = createFileRoute(
  '/admin/loja/cardapio',
)()
const AdminLojaBannersLazyRouteImport = createFileRoute('/admin/loja/banners')()
const AdminLojaAuditoriaLazyRouteImport = createFileRoute(
  '/admin/loja/auditoria',
)()
const AdminLojaAparenciaLazyRouteImport = createFileRoute(
  '/admin/loja/aparencia',
)()

const ResetarSenhaLazyRoute = ResetarSenhaLazyRouteImport.update({
  id: '/resetar-senha',
  path: '/resetar-senha',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/resetar-senha.lazy').then((d) => d.Route))
const MinhaContaLazyRoute = MinhaContaLazyRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/minha-conta.lazy').then((d) => d.Route))
const MeusPedidosLazyRoute = MeusPedidosLazyRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/meus-pedidos.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const EsqueciSenhaLazyRoute = EsqueciSenhaLazyRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/esqueci-senha.lazy').then((d) => d.Route))
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.index.lazy').then((d) => d.Route))
const LojaSlugLazyRoute = LojaSlugLazyRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/loja.$slug.lazy').then((d) => d.Route))
const AdminLojasLazyRoute = AdminLojasLazyRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.lojas.lazy').then((d) => d.Route))
const AdminLojaRoute = AdminLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaIndexLazyRoute = AdminLojaIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.index.lazy').then((d) => d.Route),
)
const AdminLojaSegurancaLazyRoute = AdminLojaSegurancaLazyRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.seguranca.lazy').then((d) => d.Route),
)
const AdminLojaPedidosLazyRoute = AdminLojaPedidosLazyRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.pedidos.lazy').then((d) => d.Route),
)
const AdminLojaGaleriaLazyRoute = AdminLojaGaleriaLazyRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.galeria.lazy').then((d) => d.Route),
)
const AdminLojaEquipeLazyRoute = AdminLojaEquipeLazyRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.equipe.lazy').then((d) => d.Route),
)
const AdminLojaConfiguracoesLazyRoute =
  AdminLojaConfiguracoesLazyRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AdminLojaRoute,
  } as any).lazy(() =>
    import('./routes/admin.loja.configuracoes.lazy').then((d) => d.Route),
  )
const AdminLojaCategoriasLazyRoute = AdminLojaCategoriasLazyRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.categorias.lazy').then((d) => d.Route),
)
const AdminLojaCardapioLazyRoute = AdminLojaCardapioLazyRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.cardapio.lazy').then((d) => d.Route),
)
const AdminLojaBannersLazyRoute = AdminLojaBannersLazyRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.banners.lazy').then((d) => d.Route),
)
const AdminLojaAuditoriaLazyRoute = AdminLojaAuditoriaLazyRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.auditoria.lazy').then((d) => d.Route),
)
const AdminLojaAparenciaLazyRoute = AdminLojaAparenciaLazyRouteImport.update({
  id: '/aparencia',
  path: '/aparencia',
  getParentRoute: () => AdminLojaRoute,
} as any).lazy(() =>
  import('./routes/admin.loja.aparencia.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaLazyRoute
  '/login': typeof LoginLazyRoute
  '/meus-pedidos': typeof MeusPedidosLazyRoute
  '/minha-conta': typeof MinhaContaLazyRoute
  '/resetar-senha': typeof ResetarSenhaLazyRoute
  '/admin/loja': typeof AdminLojaRouteWithChildren
  '/admin/lojas': typeof AdminLojasLazyRoute
  '/loja/$slug': typeof LojaSlugLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/admin/loja/aparencia': typeof AdminLojaAparenciaLazyRoute
  '/admin/loja/auditoria': typeof AdminLojaAuditoriaLazyRoute
  '/admin/loja/banners': typeof AdminLojaBannersLazyRoute
  '/admin/loja/cardapio': typeof AdminLojaCardapioLazyRoute
  '/admin/loja/categorias': typeof AdminLojaCategoriasLazyRoute
  '/admin/loja/configuracoes': typeof AdminLojaConfiguracoesLazyRoute
  '/admin/loja/equipe': typeof AdminLojaEquipeLazyRoute
  '/admin/loja/galeria': typeof AdminLojaGaleriaLazyRoute
  '/admin/loja/pedidos': typeof AdminLojaPedidosLazyRoute
  '/admin/loja/seguranca': typeof AdminLojaSegurancaLazyRoute
  '/admin/loja/': typeof AdminLojaIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/esqueci-senha': typeof EsqueciSenhaLazyRoute
  '/login': typeof LoginLazyRoute
  '/meus-pedidos': typeof MeusPedidosLazyRoute
  '/minha-conta': typeof MinhaContaLazyRoute
  '/resetar-senha': typeof ResetarSenhaLazyRoute
  '/admin/lojas': typeof AdminLojasLazyRoute
  '/loja/$slug': typeof LojaSlugLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/admin/loja/aparencia': typeof AdminLojaAparenciaLazyRoute
  '/admin/loja/auditoria': typeof AdminLojaAuditoriaLazyRoute
  '/admin/loja/banners': typeof AdminLojaBannersLazyRoute
  '/admin/loja/cardapio': typeof AdminLojaCardapioLazyRoute
  '/admin/loja/categorias': typeof AdminLojaCategoriasLazyRoute
  '/admin/loja/configuracoes': typeof AdminLojaConfiguracoesLazyRoute
  '/admin/loja/equipe': typeof AdminLojaEquipeLazyRoute
  '/admin/loja/galeria': typeof AdminLojaGaleriaLazyRoute
  '/admin/loja/pedidos': typeof AdminLojaPedidosLazyRoute
  '/admin/loja/seguranca': typeof AdminLojaSegurancaLazyRoute
  '/admin/loja': typeof AdminLojaIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaLazyRoute
  '/login': typeof LoginLazyRoute
  '/meus-pedidos': typeof MeusPedidosLazyRoute
  '/minha-conta': typeof MinhaContaLazyRoute
  '/resetar-senha': typeof ResetarSenhaLazyRoute
  '/admin/loja': typeof AdminLojaRouteWithChildren
  '/admin/lojas': typeof AdminLojasLazyRoute
  '/loja/$slug': typeof LojaSlugLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/admin/loja/aparencia': typeof AdminLojaAparenciaLazyRoute
  '/admin/loja/auditoria': typeof AdminLojaAuditoriaLazyRoute
  '/admin/loja/banners': typeof AdminLojaBannersLazyRoute
  '/admin/loja/cardapio': typeof AdminLojaCardapioLazyRoute
  '/admin/loja/categorias': typeof AdminLojaCategoriasLazyRoute
  '/admin/loja/configuracoes': typeof AdminLojaConfiguracoesLazyRoute
  '/admin/loja/equipe': typeof AdminLojaEquipeLazyRoute
  '/admin/loja/galeria': typeof AdminLojaGaleriaLazyRoute
  '/admin/loja/pedidos': typeof AdminLojaPedidosLazyRoute
  '/admin/loja/seguranca': typeof AdminLojaSegurancaLazyRoute
  '/admin/loja/': typeof AdminLojaIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/esqueci-senha'
    | '/login'
    | '/meus-pedidos'
    | '/minha-conta'
    | '/resetar-senha'
    | '/admin/loja'
    | '/admin/lojas'
    | '/loja/$slug'
    | '/admin/'
    | '/admin/loja/aparencia'
    | '/admin/loja/auditoria'
    | '/admin/loja/banners'
    | '/admin/loja/cardapio'
    | '/admin/loja/categorias'
    | '/admin/loja/configuracoes'
    | '/admin/loja/equipe'
    | '/admin/loja/galeria'
    | '/admin/loja/pedidos'
    | '/admin/loja/seguranca'
    | '/admin/loja/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/meus-pedidos'
    | '/minha-conta'
    | '/resetar-senha'
    | '/admin/lojas'
    | '/loja/$slug'
    | '/admin'
    | '/admin/loja/aparencia'
    | '/admin/loja/auditoria'
    | '/admin/loja/banners'
    | '/admin/loja/cardapio'
    | '/admin/loja/categorias'
    | '/admin/loja/configuracoes'
    | '/admin/loja/equipe'
    | '/admin/loja/galeria'
    | '/admin/loja/pedidos'
    | '/admin/loja/seguranca'
    | '/admin/loja'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/esqueci-senha'
    | '/login'
    | '/meus-pedidos'
    | '/minha-conta'
    | '/resetar-senha'
    | '/admin/loja'
    | '/admin/lojas'
    | '/loja/$slug'
    | '/admin/'
    | '/admin/loja/aparencia'
    | '/admin/loja/auditoria'
    | '/admin/loja/banners'
    | '/admin/loja/cardapio'
    | '/admin/loja/categorias'
    | '/admin/loja/configuracoes'
    | '/admin/loja/equipe'
    | '/admin/loja/galeria'
    | '/admin/loja/pedidos'
    | '/admin/loja/seguranca'
    | '/admin/loja/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminRoute: typeof AdminRouteWithChildren
  EsqueciSenhaLazyRoute: typeof EsqueciSenhaLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  MeusPedidosLazyRoute: typeof MeusPedidosLazyRoute
  MinhaContaLazyRoute: typeof MinhaContaLazyRoute
  ResetarSenhaLazyRoute: typeof ResetarSenhaLazyRoute
  LojaSlugLazyRoute: typeof LojaSlugLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resetar-senha': {
      id: '/resetar-senha'
      path: '/resetar-senha'
      fullPath: '/resetar-senha'
      preLoaderRoute: typeof ResetarSenhaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lojas': {
      id: '/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AdminLojasLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja': {
      id: '/admin/loja'
      path: '/loja'
      fullPath: '/admin/loja'
      preLoaderRoute: typeof AdminLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja/': {
      id: '/admin/loja/'
      path: '/'
      fullPath: '/admin/loja/'
      preLoaderRoute: typeof AdminLojaIndexLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/seguranca': {
      id: '/admin/loja/seguranca'
      path: '/seguranca'
      fullPath: '/admin/loja/seguranca'
      preLoaderRoute: typeof AdminLojaSegurancaLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/pedidos': {
      id: '/admin/loja/pedidos'
      path: '/pedidos'
      fullPath: '/admin/loja/pedidos'
      preLoaderRoute: typeof AdminLojaPedidosLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/galeria': {
      id: '/admin/loja/galeria'
      path: '/galeria'
      fullPath: '/admin/loja/galeria'
      preLoaderRoute: typeof AdminLojaGaleriaLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/equipe': {
      id: '/admin/loja/equipe'
      path: '/equipe'
      fullPath: '/admin/loja/equipe'
      preLoaderRoute: typeof AdminLojaEquipeLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/configuracoes': {
      id: '/admin/loja/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/loja/configuracoes'
      preLoaderRoute: typeof AdminLojaConfiguracoesLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/categorias': {
      id: '/admin/loja/categorias'
      path: '/categorias'
      fullPath: '/admin/loja/categorias'
      preLoaderRoute: typeof AdminLojaCategoriasLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/cardapio': {
      id: '/admin/loja/cardapio'
      path: '/cardapio'
      fullPath: '/admin/loja/cardapio'
      preLoaderRoute: typeof AdminLojaCardapioLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/banners': {
      id: '/admin/loja/banners'
      path: '/banners'
      fullPath: '/admin/loja/banners'
      preLoaderRoute: typeof AdminLojaBannersLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/auditoria': {
      id: '/admin/loja/auditoria'
      path: '/auditoria'
      fullPath: '/admin/loja/auditoria'
      preLoaderRoute: typeof AdminLojaAuditoriaLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
    '/admin/loja/aparencia': {
      id: '/admin/loja/aparencia'
      path: '/aparencia'
      fullPath: '/admin/loja/aparencia'
      preLoaderRoute: typeof AdminLojaAparenciaLazyRouteImport
      parentRoute: typeof AdminLojaRoute
    }
  }
}

interface AdminLojaRouteChildren {
  AdminLojaAparenciaLazyRoute: typeof AdminLojaAparenciaLazyRoute
  AdminLojaAuditoriaLazyRoute: typeof AdminLojaAuditoriaLazyRoute
  AdminLojaBannersLazyRoute: typeof AdminLojaBannersLazyRoute
  AdminLojaCardapioLazyRoute: typeof AdminLojaCardapioLazyRoute
  AdminLojaCategoriasLazyRoute: typeof AdminLojaCategoriasLazyRoute
  AdminLojaConfiguracoesLazyRoute: typeof AdminLojaConfiguracoesLazyRoute
  AdminLojaEquipeLazyRoute: typeof AdminLojaEquipeLazyRoute
  AdminLojaGaleriaLazyRoute: typeof AdminLojaGaleriaLazyRoute
  AdminLojaPedidosLazyRoute: typeof AdminLojaPedidosLazyRoute
  AdminLojaSegurancaLazyRoute: typeof AdminLojaSegurancaLazyRoute
  AdminLojaIndexLazyRoute: typeof AdminLojaIndexLazyRoute
}

const AdminLojaRouteChildren: AdminLojaRouteChildren = {
  AdminLojaAparenciaLazyRoute: AdminLojaAparenciaLazyRoute,
  AdminLojaAuditoriaLazyRoute: AdminLojaAuditoriaLazyRoute,
  AdminLojaBannersLazyRoute: AdminLojaBannersLazyRoute,
  AdminLojaCardapioLazyRoute: AdminLojaCardapioLazyRoute,
  AdminLojaCategoriasLazyRoute: AdminLojaCategoriasLazyRoute,
  AdminLojaConfiguracoesLazyRoute: AdminLojaConfiguracoesLazyRoute,
  AdminLojaEquipeLazyRoute: AdminLojaEquipeLazyRoute,
  AdminLojaGaleriaLazyRoute: AdminLojaGaleriaLazyRoute,
  AdminLojaPedidosLazyRoute: AdminLojaPedidosLazyRoute,
  AdminLojaSegurancaLazyRoute: AdminLojaSegurancaLazyRoute,
  AdminLojaIndexLazyRoute: AdminLojaIndexLazyRoute,
}

const AdminLojaRouteWithChildren = AdminLojaRoute._addFileChildren(
  AdminLojaRouteChildren,
)

interface AdminRouteChildren {
  AdminLojaRoute: typeof AdminLojaRouteWithChildren
  AdminLojasLazyRoute: typeof AdminLojasLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLojaRoute: AdminLojaRouteWithChildren,
  AdminLojasLazyRoute: AdminLojasLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminRoute: AdminRouteWithChildren,
  EsqueciSenhaLazyRoute: EsqueciSenhaLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  MeusPedidosLazyRoute: MeusPedidosLazyRoute,
  MinhaContaLazyRoute: MinhaContaLazyRoute,
  ResetarSenhaLazyRoute: ResetarSenhaLazyRoute,
  LojaSlugLazyRoute: LojaSlugLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
